# Docker Compose para EduStreaming

services:
  edustreaming:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edustreaming-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edustreaming.rule=Host(`edustreaming.local`)"
      - "traefik.http.services.edustreaming.loadbalancer.server.port=80"
    networks:
      - edustreaming-network

  # Para desarrollo local con hot reload
  edustreaming-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edustreaming-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    profiles:
      - dev

networks:
  edustreaming-network:
    driver: bridge
